// GENERATED by scripts/art-import.mjs — do not edit by hand; re-run the script.
// Every colour is a token class: the art follows the theme (globals.css).

export interface ArtProps {
  className?: string
}

/** Feixe perfurante — b1-feixe-perfurante.svg */
export function BeamPiercing({ className }: ArtProps) {
  return (
    <svg viewBox="0 0 360 280" aria-hidden="true" focusable="false" className={className}>
      <rect fillOpacity="0.35" x="32" y="200" width="296" height="16" className="fill-art-earth" />
      <line fill="none" strokeWidth="1" x1="48" y1="144" x2="178" y2="144" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="192" y1="138" x2="312" y2="138" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="80" y1="112" x2="166" y2="112" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="180" y1="106" x2="280" y2="106" className="stroke-art-line" />
      <polygon fillOpacity="0.85" points="200,208 216,208 152,56" className="fill-art-brass" />
      <line fill="none" strokeWidth="1.5" strokeDasharray="4 4" x1="149" y1="48" x2="140" y2="24" className="stroke-art-brass" />
      <circle fill="none" strokeWidth="1" cx="152" cy="56" r="16" className="stroke-art-brass" />
      <circle fillOpacity="0.85" cx="152" cy="56" r="5" className="fill-art-brass" />
      <rect fillOpacity="0.85" x="40" y="176" width="24" height="72" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="72" y="200" width="32" height="48" className="fill-art-olive" />
      <rect fillOpacity="0.85" x="112" y="160" width="16" height="88" className="fill-art-mass" />
      <rect fillOpacity="0.6" x="136" y="192" width="40" height="56" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="184" y="208" width="48" height="40" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="240" y="168" width="24" height="80" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="272" y="192" width="32" height="56" className="fill-art-olive" />
      <rect fillOpacity="0.6" x="304" y="184" width="16" height="64" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="240" y="164" width="4" height="4" className="fill-art-signal" />
      <line fill="none" strokeWidth="1.5" x1="32" y1="248" x2="328" y2="248" className="stroke-art-line" />
    </svg>
  )
}

/** Abóbada rompida — b2-abobada-rompida.svg */
export function BrokenVault({ className }: ArtProps) {
  return (
    <svg viewBox="0 0 360 280" aria-hidden="true" focusable="false" className={className}>
      <path fillOpacity="0.35" d="M36 248A144 144 0 0 1 324 248Z" className="fill-art-mass" />
      <path fillOpacity="0.6" d="M116 248A64 64 0 0 1 244 248Z" className="fill-art-earth" />
      <path fill="none" strokeWidth="1.5" d="M36 248A144 144 0 0 1 324 248" className="stroke-art-line" />
      <path fill="none" strokeWidth="1" d="M76 248A104 104 0 0 1 284 248" className="stroke-art-line" />
      <path fill="none" strokeWidth="1" d="M116 248A64 64 0 0 1 244 248" className="stroke-art-line" />
      <line fill="none" strokeWidth="10" x1="180" y1="248" x2="157" y2="64" className="stroke-background" />
      <polygon fillOpacity="0.85" points="176,248 184,248 156,56" className="fill-art-brass" />
      <circle fill="none" strokeWidth="1" cx="156" cy="56" r="20" className="stroke-art-brass" />
      <circle fillOpacity="0.85" cx="156" cy="56" r="8" className="fill-art-brass" />
      <rect fillOpacity="0.85" x="48" y="216" width="32" height="32" className="fill-art-olive" />
      <polygon fillOpacity="0.85" points="280,248 312,248 296,216" className="fill-art-deep" />
      <line fill="none" strokeWidth="1.5" x1="32" y1="248" x2="328" y2="248" className="stroke-art-line" />
    </svg>
  )
}

/** Coluna de luz — b3-coluna-de-luz.svg */
export function LightColumn({ className }: ArtProps) {
  return (
    <svg viewBox="0 0 360 280" aria-hidden="true" focusable="false" className={className}>
      <rect fillOpacity="0.35" x="264" y="32" width="64" height="48" className="fill-art-mass" />
      <line fill="none" strokeWidth="1" x1="32" y1="64" x2="200" y2="64" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="216" y1="72" x2="328" y2="72" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="32" y1="104" x2="200" y2="104" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="216" y1="112" x2="328" y2="112" className="stroke-art-line" />
      <line fill="none" strokeWidth="1.5" x1="32" y1="152" x2="200" y2="152" className="stroke-art-line" />
      <line fill="none" strokeWidth="1.5" x1="216" y1="160" x2="328" y2="160" className="stroke-art-line" />
      <rect fillOpacity="0.85" x="204" y="64" width="8" height="136" className="fill-art-brass" />
      <polygon fillOpacity="0.85" points="208,32 224,48 208,64 192,48" className="fill-art-brass" />
      <rect fillOpacity="0.85" x="32" y="192" width="88" height="56" className="fill-art-deep" />
      <rect fillOpacity="0.85" x="128" y="216" width="64" height="32" className="fill-art-olive" />
      <rect fillOpacity="0.85" x="192" y="200" width="32" height="48" className="fill-art-earth" />
      <rect fillOpacity="0.85" x="232" y="208" width="96" height="40" className="fill-art-mass" />
      <line fill="none" strokeWidth="1" x1="120" y1="160" x2="120" y2="248" className="stroke-art-line" />
      <line fill="none" strokeWidth="6" opacity="0.8" x1="32" y1="248" x2="328" y2="248" className="stroke-art-line" />
    </svg>
  )
}

/** Luas gêmeas — c1-luas-gemeas.svg */
export function TwinMoons({ className }: ArtProps) {
  return (
    <svg viewBox="0 0 360 280" aria-hidden="true" focusable="false" className={className}>
      <path fill="none" strokeWidth="1" d="M186 150A80 80 0 0 1 176 60" className="stroke-art-line" />
      <path fill="none" strokeWidth="1" d="M170 162A100 100 0 0 1 158 50" className="stroke-art-line" />
      <path fill="none" strokeWidth="1" d="M154 174A120 120 0 0 1 140 40" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="212" y1="72" x2="120" y2="36" className="stroke-art-leaf" />
      <path fillOpacity="0.85" d="M273 125.1A44 44 0 1 1 240.6 52A40 40 0 0 0 273 125.1Z" className="fill-foreground" />
      <path fillOpacity="0.85" d="M277.1 95.3A16 16 0 1 1 262.9 74A13 13 0 1 0 277.1 95.3Z" className="fill-art-brass" />
      <path fillOpacity="0.6" d="M32 248V247.8A360 360 0 0 1 328 247.8V248Z" className="fill-art-earth" />
      <line fill="none" strokeWidth="1.5" strokeDasharray="4 4" x1="104" y1="192" x2="212" y2="112" className="stroke-art-brass" />
      <ellipse fill="none" strokeWidth="1.5" cx="96" cy="204" rx="16" ry="4" className="stroke-art-brass" />
      <ellipse fill="none" strokeWidth="1" cx="96" cy="194" rx="8" ry="2" className="stroke-art-brass" />
      <line fill="none" strokeWidth="1" x1="96" y1="190" x2="96" y2="212" className="stroke-art-brass" />
      <line fill="none" strokeWidth="1.5" x1="32" y1="248" x2="328" y2="248" className="stroke-art-line" />
    </svg>
  )
}

/** Chegada ao vazio — c2-chegada-ao-vazio.svg */
export function ArrivalAtVoid({ className }: ArtProps) {
  return (
    <svg viewBox="0 0 360 280" aria-hidden="true" focusable="false" className={className}>
      <path fillOpacity="0.6" d="M0 280V160A120 120 0 0 1 120 280Z" className="fill-art-earth" />
      <path fill="none" strokeWidth="1" d="M0 136A144 144 0 0 1 144 280" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="200" y1="24" x2="328" y2="104" className="stroke-art-leaf" />
      <line fill="none" strokeWidth="1" x1="184" y1="32" x2="312" y2="112" className="stroke-art-leaf" />
      <line fill="none" strokeWidth="1" x1="168" y1="40" x2="296" y2="120" className="stroke-art-leaf" />
      <circle fillOpacity="0.85" cx="256" cy="80" r="40" className="fill-art-mass" />
      <circle fill="none" strokeWidth="1.5" cx="296" cy="112" r="24" className="stroke-art-brass" />
      <circle fillOpacity="0.6" cx="296" cy="112" r="24" className="fill-art-brass" />
      <line fill="none" strokeWidth="6" opacity="0.8" x1="104" y1="176" x2="224" y2="104" className="stroke-art-line" />
      <rect fillOpacity="0.85" x="92" y="176" width="16" height="8" transform="rotate(-31 100 180)" className="fill-art-signal" />
    </svg>
  )
}

/** Vazio vertical — c3-vazio-vertical.svg */
export function VerticalVoid({ className }: ArtProps) {
  return (
    <svg viewBox="0 0 360 280" aria-hidden="true" focusable="false" className={className}>
      <rect fillOpacity="0.85" x="256" y="40" width="48" height="48" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="280" y="60" width="24" height="24" className="fill-art-brass" />
      <rect fillOpacity="0.6" x="256" y="40" width="12" height="48" className="fill-foreground" />
      <line fill="none" strokeWidth="6" opacity="0.8" x1="240" y1="32" x2="240" y2="216" className="stroke-art-line" />
      <line fill="none" strokeWidth="1.5" x1="240" y1="104" x2="328" y2="104" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="32" y1="72" x2="240" y2="72" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="120" y1="72" x2="120" y2="216" className="stroke-art-line" />
      <rect fillOpacity="0.6" x="32" y="216" width="296" height="32" className="fill-art-earth" />
      <rect fillOpacity="0.85" x="72" y="200" width="32" height="8" className="fill-art-deep" />
      <line fill="none" strokeWidth="1" x1="88" y1="184" x2="88" y2="216" className="stroke-art-brass" />
      <line fill="none" strokeWidth="1.5" x1="32" y1="248" x2="328" y2="248" className="stroke-art-line" />
    </svg>
  )
}

/** Contemplação — d1-contemplacao.svg */
export function Contemplation({ className }: ArtProps) {
  return (
    <svg viewBox="0 0 360 280" aria-hidden="true" focusable="false" className={className}>
      <circle fillOpacity="0.6" cx="48" cy="40" r="1" className="fill-foreground" />
      <circle cx="64" cy="80" r="1.5" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="104" cy="56" r="1" className="fill-foreground" />
      <circle cx="136" cy="32" r="1.5" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="160" cy="96" r="1" className="fill-foreground" />
      <circle cx="208" cy="40" r="1.5" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="232" cy="76" r="1" className="fill-foreground" />
      <circle cx="264" cy="56" r="1.5" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="296" cy="96" r="1" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="312" cy="40" r="1" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="40" cy="104" r="1" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="120" cy="88" r="1" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="328" cy="72" r="1" className="fill-foreground" />
      <path fillOpacity="0.85" d="M32 141.5A520 520 0 0 1 328 141.5L328 183.4A480 480 0 0 0 32 183.4Z" className="fill-art-deep" />
      <path fill="none" strokeWidth="1" d="M32 141.5A520 520 0 0 1 328 141.5" className="stroke-foreground" />
      <rect fillOpacity="0.35" x="32" y="208" width="40" height="40" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="72" y="208" width="216" height="40" className="fill-art-mass" />
      <rect fillOpacity="0.35" x="288" y="208" width="40" height="40" className="fill-art-mass" />
      <circle fillOpacity="0.6" cx="44" cy="202" r="3" className="fill-art-leaf" />
      <circle fillOpacity="0.6" cx="58" cy="198" r="3" className="fill-art-leaf" />
      <circle fillOpacity="0.6" cx="74" cy="203" r="3" className="fill-art-leaf" />
      <circle fillOpacity="0.6" cx="270" cy="200" r="3" className="fill-art-leaf" />
      <circle fillOpacity="0.6" cx="286" cy="196" r="3" className="fill-art-leaf" />
      <circle fillOpacity="0.6" cx="304" cy="202" r="3" className="fill-art-leaf" />
      <circle fillOpacity="0.6" cx="318" cy="198" r="3" className="fill-art-leaf" />
      <polygon fillOpacity="0.85" points="180,148 164,224 196,224" className="fill-art-brass" />
      <circle fillOpacity="0.85" cx="180" cy="138" r="8" className="fill-art-brass" />
      <line fill="none" strokeWidth="1.5" x1="32" y1="248" x2="328" y2="248" className="stroke-art-line" />
    </svg>
  )
}

/** A única — d2-a-unica.svg */
export function TheOnlyOne({ className }: ArtProps) {
  return (
    <svg viewBox="0 0 360 280" aria-hidden="true" focusable="false" className={className}>
      <circle fillOpacity="0.6" cx="48" cy="40" r="1" className="fill-foreground" />
      <circle cx="64" cy="88" r="1.5" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="96" cy="56" r="1" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="120" cy="112" r="1" className="fill-foreground" />
      <circle cx="136" cy="32" r="1.5" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="176" cy="72" r="1" className="fill-foreground" />
      <circle cx="208" cy="40" r="1.5" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="232" cy="96" r="1" className="fill-foreground" />
      <circle cx="264" cy="60" r="1.5" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="288" cy="112" r="1" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="304" cy="44" r="1" className="fill-foreground" />
      <circle cx="320" cy="84" r="1.5" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="88" cy="128" r="1" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="40" cy="120" r="1" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="248" cy="136" r="1" className="fill-foreground" />
      <circle fillOpacity="0.6" cx="160" cy="120" r="1" className="fill-foreground" />
      <circle fill="none" strokeWidth="1" cx="196" cy="100" r="76" className="stroke-art-line" />
      <line fill="none" strokeWidth="1.5" x1="32" y1="222" x2="328" y2="198" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="32" y1="232" x2="328" y2="208" className="stroke-art-line" />
      <rect fillOpacity="0.85" x="238" y="185" width="6" height="20" transform="rotate(-4.6 241 205)" className="fill-art-signal" />
    </svg>
  )
}

/** Janela — d3-janela.svg */
export function Window({ className }: ArtProps) {
  return (
    <svg viewBox="0 0 360 280" aria-hidden="true" focusable="false" className={className}>
      <rect fill="none" strokeWidth="1.5" x="32" y="32" width="296" height="216" className="stroke-art-line" />
      <rect x="56" y="52" width="3" height="3" className="fill-foreground" />
      <rect fillOpacity="0.6" x="88" y="92" width="2" height="2" className="fill-foreground" />
      <rect x="128" y="60" width="3" height="3" className="fill-foreground" />
      <rect fillOpacity="0.6" x="160" y="120" width="2" height="2" className="fill-foreground" />
      <rect x="184" y="44" width="3" height="3" className="fill-foreground" />
      <rect fillOpacity="0.6" x="216" y="84" width="2" height="2" className="fill-foreground" />
      <rect x="248" y="56" width="3" height="3" className="fill-foreground" />
      <rect fillOpacity="0.6" x="264" y="124" width="2" height="2" className="fill-foreground" />
      <rect fillOpacity="0.6" x="72" y="136" width="2" height="2" className="fill-foreground" />
      <rect x="112" y="112" width="3" height="3" className="fill-foreground" />
      <rect fillOpacity="0.6" x="232" y="148" width="2" height="2" className="fill-foreground" />
      <rect fillOpacity="0.6" x="48" y="96" width="2" height="2" className="fill-foreground" />
      <rect fillOpacity="0.85" x="32" y="184" width="296" height="16" className="fill-art-deep" />
      <line fill="none" strokeWidth="1" x1="32" y1="184" x2="328" y2="184" className="stroke-foreground" />
      <rect fillOpacity="0.85" x="32" y="216" width="296" height="32" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="88" y="176" width="8" height="40" className="fill-art-brass" />
    </svg>
  )
}

/** Olho guardião — e1-olho-guardiao.svg */
export function GuardianEye({ className }: ArtProps) {
  return (
    <svg viewBox="0 0 360 280" aria-hidden="true" focusable="false" className={className}>
      <path fillOpacity="0.35" d="M32 87.9A224 224 0 0 1 328 87.9L328 0L32 0Z" className="fill-art-earth" />
      <path fill="none" strokeWidth="1" d="M87.3 91.2A96 96 0 0 1 272.7 91.2" className="stroke-art-line" />
      <path fill="none" strokeWidth="1" d="M107.5 82.2A80 80 0 0 1 252.5 82.2" className="stroke-art-line" />
      <path fill="none" strokeWidth="1" d="M127.6 79.3A64 64 0 0 1 232.4 79.3" className="stroke-art-line" />
      <circle fill="none" strokeWidth="1.5" cx="180" cy="116" r="44" className="stroke-art-line" />
      <circle fillOpacity="0.85" cx="180" cy="116" r="28" className="fill-art-earth" />
      <circle fillOpacity="0.85" cx="180" cy="116" r="13" className="fill-art-brass" />
      <circle fillOpacity="0.6" cx="180" cy="116" r="4" className="fill-foreground" />
      <circle fillOpacity="0.85" cx="180" cy="60" r="2.5" className="fill-art-brass" />
      <circle fillOpacity="0.85" cx="208" cy="67.5" r="2.5" className="fill-art-brass" />
      <circle fillOpacity="0.85" cx="228.5" cy="88" r="2.5" className="fill-art-brass" />
      <circle fillOpacity="0.85" cx="236" cy="116" r="2.5" className="fill-art-brass" />
      <circle fillOpacity="0.85" cx="228.5" cy="144" r="2.5" className="fill-art-brass" />
      <circle fillOpacity="0.85" cx="208" cy="164.5" r="2.5" className="fill-art-brass" />
      <circle fillOpacity="0.85" cx="180" cy="172" r="2.5" className="fill-art-brass" />
      <circle fillOpacity="0.85" cx="152" cy="164.5" r="2.5" className="fill-art-brass" />
      <circle fillOpacity="0.85" cx="131.5" cy="144" r="2.5" className="fill-art-brass" />
      <circle fillOpacity="0.85" cx="124" cy="116" r="2.5" className="fill-art-brass" />
      <circle fillOpacity="0.85" cx="131.5" cy="88" r="2.5" className="fill-art-brass" />
      <circle fillOpacity="0.85" cx="152" cy="67.5" r="2.5" className="fill-art-brass" />
      <rect fillOpacity="0.6" x="40" y="180" width="28" height="6" className="fill-art-mass" />
      <rect fillOpacity="0.6" x="82" y="180" width="28" height="6" className="fill-art-mass" />
      <rect fillOpacity="0.6" x="124" y="180" width="28" height="6" className="fill-art-mass" />
      <rect fillOpacity="0.6" x="166" y="180" width="28" height="6" className="fill-art-mass" />
      <rect fillOpacity="0.6" x="208" y="180" width="28" height="6" className="fill-art-mass" />
      <rect fillOpacity="0.6" x="250" y="180" width="28" height="6" className="fill-art-mass" />
      <rect fillOpacity="0.6" x="292" y="180" width="28" height="6" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="32" y="198" width="36" height="8" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="84" y="198" width="36" height="8" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="136" y="198" width="36" height="8" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="188" y="198" width="36" height="8" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="240" y="198" width="36" height="8" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="292" y="198" width="36" height="8" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="61" y="220" width="46" height="10" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="125" y="220" width="46" height="10" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="189" y="220" width="46" height="10" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="253" y="220" width="46" height="10" className="fill-art-mass" />
      <rect fillOpacity="0.6" x="34" y="244" width="58" height="12" className="fill-art-mass" />
      <rect fillOpacity="0.6" x="112" y="244" width="58" height="12" className="fill-art-mass" />
      <rect fillOpacity="0.6" x="190" y="244" width="58" height="12" className="fill-art-mass" />
      <rect fillOpacity="0.6" x="268" y="244" width="58" height="12" className="fill-art-mass" />
      <line fill="none" strokeWidth="1" x1="32" y1="172" x2="328" y2="172" className="stroke-art-line" />
    </svg>
  )
}

/** A vigília — e2-a-vigilia.svg */
export function Vigil({ className }: ArtProps) {
  return (
    <svg viewBox="0 0 360 280" aria-hidden="true" focusable="false" className={className}>
      <path fillOpacity="0.35" d="M32 87.9A224 224 0 0 1 328 87.9L328 0L32 0Z" className="fill-art-earth" />
      <line fill="none" strokeWidth="1" x1="180" y1="112" x2="32.3" y2="86" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="180" y1="112" x2="46.3" y2="43.9" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="180" y1="112" x2="72.1" y2="7.8" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="180" y1="112" x2="107.3" y2="-19.2" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="180" y1="112" x2="148.8" y2="-34.7" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="180" y1="112" x2="193.1" y2="-37.4" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="180" y1="112" x2="236.2" y2="-27.1" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="180" y1="112" x2="274.4" y2="-4.6" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="180" y1="112" x2="304.4" y2="28.1" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="180" y1="112" x2="323.4" y2="68.1" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="32" y1="248" x2="168" y2="124" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="328" y1="248" x2="192" y2="124" className="stroke-art-line" />
      <line fill="none" strokeWidth="6" opacity="0.8" x1="56" y1="216" x2="304" y2="216" className="stroke-art-line" />
      <line fill="none" strokeWidth="1.5" x1="88" y1="184" x2="272" y2="184" className="stroke-art-line" />
      <line fill="none" strokeWidth="1" x1="112" y1="160" x2="248" y2="160" className="stroke-art-line" />
      <circle fillOpacity="0.85" cx="180" cy="112" r="40" className="fill-art-mass" />
      <circle fill="none" strokeWidth="1.5" cx="180" cy="112" r="40" className="stroke-art-line" />
      <circle fill="none" strokeWidth="1" cx="180" cy="112" r="24" className="stroke-art-brass" />
      <circle fillOpacity="0.85" cx="180" cy="112" r="11" className="fill-art-signal" />
    </svg>
  )
}

/** Campo de lápides — e3-campo-de-lapides.svg */
export function TombstoneField({ className }: ArtProps) {
  return (
    <svg viewBox="0 0 360 280" aria-hidden="true" focusable="false" className={className}>
      <rect fillOpacity="0.35" x="32" y="32" width="296" height="40" className="fill-art-earth" />
      <rect fillOpacity="0.85" x="32" y="88" width="80" height="48" className="fill-art-mass" />
      <rect fillOpacity="0.6" x="120" y="88" width="48" height="24" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="248" y="88" width="80" height="24" className="fill-art-olive" />
      <rect fillOpacity="0.6" x="32" y="152" width="48" height="40" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="88" y="160" width="72" height="32" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="200" y="152" width="56" height="40" className="fill-art-earth" />
      <rect fillOpacity="0.85" x="264" y="144" width="64" height="48" className="fill-art-mass" />
      <rect fillOpacity="0.6" x="32" y="208" width="104" height="40" className="fill-art-mass" />
      <rect fillOpacity="0.85" x="144" y="208" width="72" height="40" className="fill-art-mass" />
      <rect fillOpacity="0.6" x="224" y="216" width="104" height="32" className="fill-art-olive" />
      <line fill="none" strokeWidth="6" opacity="0.8" x1="32" y1="144" x2="328" y2="144" className="stroke-art-line" />
      <line fill="none" strokeWidth="6" opacity="0.8" x1="180" y1="32" x2="180" y2="248" className="stroke-art-line" />
      <rect x="160" y="124" width="40" height="40" className="fill-background" />
      <rect fill="none" strokeWidth="1.5" x="160" y="124" width="40" height="40" className="stroke-art-line" />
      <rect fillOpacity="0.85" x="172" y="136" width="16" height="16" className="fill-art-brass" />
    </svg>
  )
}

/** Escada — g3-escada.svg */
export function Staircase({ className }: ArtProps) {
  return (
    <svg viewBox="0 0 96 96" aria-hidden="true" focusable="false" className={className}>
      <rect stroke="none" x="6" y="58" width="28" height="18" className="fill-foreground" />
      <rect stroke="none" x="34" y="38" width="28" height="18" className="fill-foreground" />
      <rect stroke="none" x="62" y="18" width="28" height="18" className="fill-art-brass" />
      <line fill="none" strokeWidth="4" x1="20" y1="86" x2="90" y2="86" className="stroke-foreground" />
    </svg>
  )
}

/** Dínamo — h1-dinamo.svg */
export function Dynamo({ className }: ArtProps) {
  return (
    <svg viewBox="0 0 96 96" aria-hidden="true" focusable="false" className={className}>
      <line fill="none" strokeWidth="9" x1="24" y1="72" x2="72" y2="24" className="stroke-art-brass" />
      <line fill="none" strokeWidth="4" x1="10" y1="46" x2="34" y2="22" className="stroke-foreground" />
      <circle stroke="none" cx="20" cy="76" r="14" className="fill-foreground" />
      <circle fill="none" strokeWidth="6" cx="76" cy="20" r="13" className="stroke-foreground" />
    </svg>
  )
}

/** Circuito — h2-circuito.svg */
export function Circuit({ className }: ArtProps) {
  return (
    <svg viewBox="0 0 96 96" aria-hidden="true" focusable="false" className={className}>
      <circle fill="none" strokeWidth="8" cx="48" cy="48" r="32" className="stroke-foreground" />
      <circle stroke="none" cx="48" cy="16" r="13" className="fill-art-brass" />
      <circle stroke="none" cx="48" cy="80" r="13" className="fill-background" />
      <circle fill="none" strokeWidth="4" cx="48" cy="80" r="13" className="stroke-foreground" />
    </svg>
  )
}

/** Laço fechado — h3-laco-fechado.svg */
export function ClosedLoop({ className }: ArtProps) {
  return (
    <svg viewBox="0 0 96 96" aria-hidden="true" focusable="false" className={className}>
      <path fill="none" strokeWidth="8" d="M14 34V14H82V82H14V58" className="stroke-foreground" />
      <rect stroke="none" x="58" y="24" width="24" height="24" className="fill-art-brass" />
      <rect stroke="none" x="24" y="58" width="20" height="24" className="fill-foreground" />
    </svg>
  )
}
